fix: Manually symlink bbmodels to destination instead of relying on a bind mount (since this creates an empty folder and git clone can't run)

diff --git a/scripts/helpers b/scripts/helpers
--- a/scripts/helpers
+++ b/scripts/helpers
@@ -3,8 +3,12 @@
 PREFIX="[Init]"
 
 log_error() {
-  echo "$PREFIX Error: $1" >&2
+  echo -e "\e[31m$PREFIX Error: $1\e[0m" >&2
   exit 1
+}
+
+log_warning() {
+  echo -e "\e[33m$PREFIX Warning: $1\e[0m"
 }
 
 log_info() {
